from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import typer
import yaml


@dataclass(frozen=True)
class ProjectDetection:
    flutter: bool
    ios: bool
    android: bool
    web: bool
    firebase: bool
    flavor_candidates: tuple[str, ...]


def detect_project(cwd: Path) -> ProjectDetection:
    flutter = (cwd / "pubspec.yaml").is_file()
    ios = (cwd / "ios").is_dir()
    android = (cwd / "android").is_dir()
    web = (cwd / "web").is_dir()
    firebase = any(
        path.exists()
        for path in (
            cwd / "firebase.json",
            cwd / "android" / "app" / "google-services.json",
            cwd / "ios" / "Runner" / "GoogleService-Info.plist",
        )
    )
    flavors = tuple(
        sorted(
            path.stem.removeprefix("main_")
            for path in (cwd / "lib").glob("main_*.dart")
            if path.stem.removeprefix("main_")
        )
    )
    return ProjectDetection(
        flutter=flutter,
        ios=ios,
        android=android,
        web=web,
        firebase=firebase,
        flavor_candidates=flavors,
    )


def build_initial_config(detection: ProjectDetection) -> dict:
    if not detection.flutter:
        raise typer.BadParameter("No Flutter project detected (pubspec.yaml is missing)")

    build_steps: list[object] = []
    if detection.ios:
        build_steps.append({"ios.flutter_build_ipa": {"artifact": "ios_ipa"}})
    if detection.android:
        build_steps.append({"android.build_aab": {"artifact": "android_aab"}})
    if detection.web:
        build_steps.append({"web.build": {"env_name": "test"}})

    steps: list[object] = ["flutter.pub_get"]
    if len(build_steps) > 1:
        steps.append({"parallel": {"steps": build_steps}})
    else:
        steps.extend(build_steps)

    return {
        "version": 1,
        "pipelines": {
            "test": {
                "risk": "standard",
                "steps": steps,
            }
        },
    }


def initialize_project(cwd: Path, *, force: bool = False) -> tuple[Path, ProjectDetection]:
    target = cwd / "cdt.yaml"
    if target.exists() and not force:
        raise typer.BadParameter("cdt.yaml already exists. Use --force to replace it")
    detection = detect_project(cwd)
    config = build_initial_config(detection)
    header = (
        "# yaml-language-server: "
        "$schema=https://raw.githubusercontent.com/Sergionius/cdt/main/cdt/cdt.schema.json\n"
        "# Generated by cdt init. Review this file before the first real run.\n"
        "# Add upload, notification, and production steps explicitly.\n"
    )
    target.write_text(
        header + yaml.safe_dump(config, allow_unicode=True, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )
    return target, detection
